In [1]:
# Import PyTorch
import torch

temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

In [2]:
temperatures = torch.tensor([[72, 75, 78], [70, 73, 76]])
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

# Check the shape of the temperatures tensor
temp_shape = temperatures.shape
print("Shape of temperatures:", temp_shape)

# Check the type of the temperatures tensor
temp_type = temperatures.dtype
print("Data type of temperatures:", temp_type)

# Adjust the temperatures by adding the adjustment tensor
corrected_temperatures = temperatures + adjustment

print("Corrected temperatures:", corrected_temperatures)

Shape of temperatures: torch.Size([2, 3])
Data type of temperatures: torch.int64
Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


In [ ]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with two linear layers
model = nn.Sequential(
    nn.Linear(8, 10),
    nn.Linear(10, 1)
)

output = model(input_tensor)
print(output)

### Sigmoid Activation Function: Used for binary classification

### Softmax Activation Function: Used for multi-class classification

In [ ]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

In [ ]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

In the training loop, we: 

1. Propogate data forward
2. Compare outputs to truth values
3. Backpropogate to update weights and biases
4. Repeat until weights and biases are tuned to produce meaningful results. 

In [3]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.0292]], grad_fn=<SigmoidBackward0>)


Create a 4-layer linear neural network compatible with input_tensor as the input, and a regression value as output.

In [ ]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 12),
    nn.Linear(12, 12),
    nn.Linear(12, 6),
    nn.Linear(6, 1)
)

output = model(input_tensor)
print(output)

Update the network provided to perform a multi-class classification with four outputs.

In [7]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.2008, 0.2121, 0.2682, 0.3189]], grad_fn=<SoftmaxBackward0>)


In [8]:
import torch.nn.functional as F

In [10]:
import numpy as np

In [23]:
y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([1, 0, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes)

In [24]:
one_hot_numpy

array([1, 0, 0])

In [25]:
one_hot_pytorch

tensor([0, 1, 0])

In [26]:
from torch.nn import CrossEntropyLoss

y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


### Accessing the model parameters

In [30]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Linear(8, 2),
                      nn.Linear(2, 1)
                     )

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[1].bias

In [31]:
weight_0, bias_1

(Parameter containing:
 tensor([[ 0.1266, -0.1751,  0.1399,  0.0688,  0.2230,  0.0831,  0.1882,  0.1348,
           0.0803, -0.1993, -0.2427,  0.2148, -0.2220,  0.1736,  0.1757, -0.1004],
         [-0.0540,  0.1005, -0.0686, -0.0669,  0.2124,  0.1541, -0.1146,  0.1207,
           0.2491, -0.0730, -0.2478, -0.2126,  0.0149,  0.0389,  0.1063,  0.0214],
         [-0.2469,  0.0112,  0.2362,  0.0835,  0.1824, -0.2401, -0.1568, -0.2191,
          -0.2046, -0.1876, -0.0402, -0.0487, -0.1378,  0.1416, -0.2055,  0.1901],
         [ 0.1929, -0.1599,  0.1892, -0.0746, -0.1819,  0.0885,  0.1846,  0.1947,
           0.0768, -0.0791, -0.2101,  0.0204, -0.0868,  0.0633, -0.2065, -0.1019],
         [-0.0597,  0.1160,  0.0674,  0.1675,  0.0646,  0.1461,  0.2106,  0.1274,
           0.0432,  0.0563, -0.1968, -0.0648, -0.2463,  0.0735, -0.1699, -0.0628],
         [ 0.2234,  0.2487,  0.2219, -0.1028,  0.0164,  0.2418, -0.1116,  0.0468,
          -0.0236,  0.1092, -0.1454,  0.1638, -0.1760, -0.0945, -0.036

In [40]:
# lr = 0.001

# weight0 = model[0].weight
# weight1 = model[1].weight
# weight2 = model[2].weight

# # Access the gradients of the weight of each linear layer
# grads0 = weight0.grad
# grads1 = weight1.grad
# grads2 = weight2.grad

# # Update the weights using the learning rate and the gradients
# weight0 = weight0 - lr * grads0
# weight1 = weight1 - lr * grads1
# weight2 = weight2 - lr * grads2

In [ ]:
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

In [41]:
y_pred = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_pred - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_pred).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


In [45]:
num_epochs=5

In [47]:
# # Loop over the number of epochs and the dataloader
# for i in range(num_epochs):
    
#     for data in dataloader:
#         # Set the gradients to zero
#         optimizer.zero_grad()
#         # Run a forward pass
#         feature, target = data
#         prediction = model(feature)    
#         # Calculate the loss
#         loss = criterion(prediction, target)    
#         # Compute the gradients
#         loss.backward()
#         # Update the model's parameters
#         optimizer.step()
    
# show_results(model, dataloader)

In [ ]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

In [ ]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

In [ ]:
model = nn.Sequential(nn.Linear(16, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for parameter in model.parameters():
    total += parameter.numel()
  
print(f"The number of parameters in the model is {total}")

Create a 4-layer linear neural network with >120 parameters, using n_features as input and n_classes as output sizes.

In [ ]:
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with more than 120 parameters
model = nn.Sequential(
    nn.Linear(n_features, 16),
    nn.Linear(16, 8),
    nn.Linear(8, 3), 
    nn.Linear(3, n_classes)
)

output = model(input_tensor)

print(calculate_capacity(model))

In [ ]:
for name, param in model.named_parameters():    
  
    # Check if the parameters belong to the first layer
    if name == '0.weight' or name == '0.bias':
      
        # Freeze the parameters
        param.requires_grad = False
  
    # Check if the parameters belong to the second layer
    if name == '1.weight' or name == '1.bias':
      
        # Freeze the parameters
        param.requires_grad = False

In [ ]:
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Use uniform initialization for layer0 and layer1 weights
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model = nn.Sequential(layer0, layer1)

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

# Create a TensorDataset from two tensors
dataset = TensorDataset(torch_features.float(), torch_target.float())

# Return the last element of this dataset
print(dataset[-1])

In [ ]:
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].to_numpy()).float()
target = torch.tensor(dataframe['Potability'].to_numpy()).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, shuffle=True, batch_size=2)
x, y = next(iter(dataloader))

# Create a model using the nn.Sequential API
model = nn.Sequential(
    nn.Linear(4, 4),
    nn.Linear(4, 1)
)
output = model(features)
print(output)

In [ ]:
# Set the model to evaluation mode
model.eval()
validation_loss = 0.0

with torch.no_grad():
  
    for data in validationloader:
    
        outputs = model(data[0])
        loss = criterion(outputs, data[1])
      
        # Sum the current loss to the validation_loss variable
        validation_loss += loss.item()
        
# Calculate the mean loss value
validation_loss_epoch = validation_loss / len(validationloader)
print(validation_loss_epoch)

# Set the model back to training mode
model.train()

In [ ]:
import torchmetrics

In [ ]:
# Create accuracy metric using torch metrics
metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for data in dataloader:
    features, labels = data
    outputs = model(features)
    
    # Calculate accuracy over the batch
    acc = metric(outputs, labels.argmax(dim=-1))
    
# Calculate accuracy over the whole epoch
acc = metric.compute()

# Reset the metric for the next epoch 
metric.reset()
plot_errors(model, dataloader)

In [ ]:
# Using the same model, set the dropout probability to 0.8
model = nn.Sequential(nn.Linear(3072, 16),
                      nn.ReLU(),
                      nn.Dropout(p=0.8))
model(input_tensor)

In [ ]:
values = []
for idx in range(10):
    # Randomly sample a learning rate factor between 2 and 4
    factor = np.random.uniform(2,4)
    lr = 10 ** -factor
    
    # Randomly select a momentum between 0.85 and 0.99
    momentum = np.random.uniform(0.85, 0.99)
    
    values.append((lr, momentum))