# Introduction to PyTorch

### Import Packages

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset

from torch.nn import CrossEntropyLoss
import torchmetrics

import numpy as np

### Creating a Tensor from a List Object

In [1]:
# Define temperature object
temperatures = [[72, 75, 78], [70, 73, 76]]

# Create a tensor from temperatures
temp_tensor = torch.tensor(temperatures)

### Update a Tensor Object

In [ ]:
# Create an adjustment object
adjustment = torch.tensor([[2, 2, 2], [2, 2, 2]])

In [ ]:
# Check the shape of the temperatures tensor
temp_shape = temperatures.shape
print("Shape of temperatures:", temp_shape)

In [ ]:
# Check the type of the temperatures tensor
temp_type = temperatures.dtype
print("Data type of temperatures:", temp_type)

In [2]:
# Adjust the temperatures by adding the adjustment tensor
corrected_temperatures = temperatures + adjustment
print("Corrected temperatures:", corrected_temperatures)

Shape of temperatures: torch.Size([2, 3])
Data type of temperatures: torch.int64
Corrected temperatures: tensor([[74, 77, 80],
        [72, 75, 78]])


### Create a simple model

In [ ]:
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with two linear layers
model = nn.Sequential(
    nn.Linear(8, 10),
    nn.Linear(10, 1)
)

output = model(input_tensor)
print(output)

### Understanding Activation Functions

1. Sigmoid Activation Function: Used for binary classification

2. Softmax Activation Function: Used for multi-class classification

### Sigmoid Example

In [ ]:
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

### Softmax Example

In [ ]:
input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax()
probabilities = softmax(input_tensor)
print(probabilities)

### Understanding the Training Loop

1. Propogate data forward
2. Compare outputs to truth values
3. Backpropogate to update weights and biases
4. Repeat until weights and biases are tuned to produce meaningful results. 

### Create a neural network for binary classification.

In [8]:
input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8, 1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.9846]], grad_fn=<SigmoidBackward0>)


### Create a 4-layer linear neural network compatible with input_tensor as the input, and a regression value as output.

In [4]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(
    nn.Linear(11, 12),
    nn.Linear(12, 12),
    nn.Linear(12, 6),
    nn.Linear(6, 1)
)

output = model(input_tensor)
print(output)

tensor([[0.0244]], grad_fn=<AddmmBackward0>)


### Update the network provided to perform a multi-class classification with four outputs.

In [7]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Update network below to perform a multi-class classification with four labels
model = nn.Sequential(
  nn.Linear(11, 20),
  nn.Linear(20, 12),
  nn.Linear(12, 6),
  nn.Linear(6, 4), 
  nn.Softmax()
)

output = model(input_tensor)
print(output)

tensor([[0.2008, 0.2121, 0.2682, 0.3189]], grad_fn=<SoftmaxBackward0>)


### One hot encoding for classification

In [23]:
y = 1
num_classes = 3

# Create the one-hot encoded vector using NumPy
one_hot_numpy = np.array([1, 0, 0])

# Create the one-hot encoded vector using PyTorch
one_hot_pytorch = F.one_hot(torch.tensor(y), num_classes)

In [24]:
one_hot_numpy

array([1, 0, 0])

In [25]:
one_hot_pytorch

tensor([0, 1, 0])

### Loss function for classification

In [26]:
y = [2]
scores = torch.tensor([[0.1, 6.0, -2.0, 3.2]])

# Create a one-hot encoded vector of the label y
one_hot_label = F.one_hot(torch.tensor(y), scores.shape[1])

# Create the cross entropy loss function
criterion = CrossEntropyLoss()

# Calculate the cross entropy loss
loss = criterion(scores.double(), one_hot_label.double())
print(loss)

tensor(8.0619, dtype=torch.float64)


### Accessing the model parameters

In [9]:
model = nn.Sequential(nn.Linear(16, 8),
                      nn.Linear(8, 2),
                      nn.Linear(2, 1)
                     )

# Access the weight of the first linear layer
weight_0 = model[0].weight

# Access the bias of the second linear layer
bias_1 = model[1].bias

In [11]:
weight_0

Parameter containing:
tensor([[ 0.0324, -0.2304, -0.1966,  0.0474,  0.1192, -0.1544, -0.0386,  0.1083,
         -0.0328,  0.2341, -0.0540,  0.1825, -0.2004, -0.1325, -0.2104,  0.2037],
        [ 0.1631, -0.1088, -0.1084, -0.2179, -0.0978,  0.2385,  0.1869,  0.0953,
          0.1931, -0.0958,  0.2163,  0.1586,  0.0521,  0.1915,  0.1213,  0.0454],
        [-0.1163, -0.0294, -0.0318, -0.2401,  0.1443,  0.0830, -0.2296,  0.2451,
         -0.0003, -0.0443, -0.2326,  0.0659, -0.1015,  0.0506, -0.2281, -0.1605],
        [-0.0925,  0.1461, -0.2062, -0.0906,  0.1633,  0.0283,  0.0614, -0.1515,
         -0.2156, -0.1510, -0.0919,  0.1340,  0.0415, -0.1377, -0.0786, -0.2489],
        [ 0.0309,  0.1957, -0.0772, -0.2007,  0.0206,  0.2474, -0.1179,  0.0868,
         -0.2385, -0.1134, -0.1803, -0.1949, -0.2072,  0.1195, -0.0040,  0.1377],
        [ 0.1394, -0.1626, -0.2166,  0.1050, -0.0863,  0.0698,  0.1126,  0.1403,
         -0.1128, -0.1202,  0.1676, -0.0717, -0.1589, -0.0641, -0.2094,  0.2407],


In [12]:
bias_1

Parameter containing:
tensor([-0.2324, -0.2417], requires_grad=True)

In [20]:
# lr = 0.001

# weight0 = model[0].weight
# weight1 = model[1].weight
# weight2 = model[2].weight

# # Access the gradients of the weight of each linear layer
# grads0 = weight0.grad
# grads1 = weight1.grad
# grads2 = weight2.grad

# # Update the weights using the learning rate and the gradients
# weight0 = weight0 - lr * grads0
# weight1 = weight1 - lr * grads1
# weight2 = weight2 - lr * grads2

In [ ]:
# Create the optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001)

loss = criterion(pred, target)
loss.backward()

# Update the model's parameters using the optimizer
optimizer.step()

In [41]:
y_pred = np.array(10)
y = np.array(1)

# Calculate the MSELoss using NumPy
mse_numpy = np.mean((y_pred - y)**2)

# Create the MSELoss function
criterion = nn.MSELoss()

# Calculate the MSELoss using the created loss function
mse_pytorch = criterion(torch.tensor(y_pred).float(), torch.tensor(y).float())
print(mse_pytorch)

tensor(81.)


In [45]:
num_epochs=5

In [47]:
# # Loop over the number of epochs and the dataloader
# for i in range(num_epochs):
    
#     for data in dataloader:
#         # Set the gradients to zero
#         optimizer.zero_grad()
#         # Run a forward pass
#         feature, target = data
#         prediction = model(feature)    
#         # Calculate the loss
#         loss = criterion(prediction, target)    
#         # Compute the gradients
#         loss.backward()
#         # Update the model's parameters
#         optimizer.step()
    
# show_results(model, dataloader)

In [ ]:
# Create a ReLU function with PyTorch
relu_pytorch = nn.ReLU()

# Apply your ReLU function on x, and calculate gradients
x = torch.tensor(-1.0, requires_grad=True)
y = relu_pytorch(x)
y.backward()

# Print the gradient of the ReLU function for x
gradient = x.grad
print(gradient)

In [ ]:
# Create a leaky relu function in PyTorch
leaky_relu_pytorch = nn.LeakyReLU(negative_slope=0.05)

x = torch.tensor(-2.0)
# Call the above function on the tensor x
output = leaky_relu_pytorch(x)
print(output)

In [ ]:
model = nn.Sequential(nn.Linear(16, 4),
                      nn.Linear(4, 2),
                      nn.Linear(2, 1))

total = 0

# Calculate the number of parameters in the model
for parameter in model.parameters():
    total += parameter.numel()
  
print(f"The number of parameters in the model is {total}")

Create a 4-layer linear neural network with >120 parameters, using n_features as input and n_classes as output sizes.

In [ ]:
n_features = 8
n_classes = 2

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Create a neural network with more than 120 parameters
model = nn.Sequential(
    nn.Linear(n_features, 16),
    nn.Linear(16, 8),
    nn.Linear(8, 3), 
    nn.Linear(3, n_classes)
)

output = model(input_tensor)

print(calculate_capacity(model))

In [ ]:
for name, param in model.named_parameters():    
  
    # Check if the parameters belong to the first layer
    if name == '0.weight' or name == '0.bias':
      
        # Freeze the parameters
        param.requires_grad = False
  
    # Check if the parameters belong to the second layer
    if name == '1.weight' or name == '1.bias':
      
        # Freeze the parameters
        param.requires_grad = False

In [ ]:
layer0 = nn.Linear(16, 32)
layer1 = nn.Linear(32, 64)

# Use uniform initialization for layer0 and layer1 weights
nn.init.uniform_(layer0.weight)
nn.init.uniform_(layer1.weight)

model = nn.Sequential(layer0, layer1)

In [ ]:
import numpy as np
import torch
from torch.utils.data import TensorDataset

np_features = np.array(np.random.rand(12, 8))
np_target = np.array(np.random.rand(12, 1))

torch_features = torch.tensor(np_features)
torch_target = torch.tensor(np_target)

# Create a TensorDataset from two tensors
dataset = TensorDataset(torch_features.float(), torch_target.float())

# Return the last element of this dataset
print(dataset[-1])

In [ ]:
# Load the different columns into two PyTorch tensors
features = torch.tensor(dataframe[['ph', 'Sulfate', 'Conductivity', 'Organic_carbon']].to_numpy()).float()
target = torch.tensor(dataframe['Potability'].to_numpy()).float()

# Create a dataset from the two generated tensors
dataset = TensorDataset(features, target)

# Create a dataloader using the above dataset
dataloader = DataLoader(dataset, shuffle=True, batch_size=2)
x, y = next(iter(dataloader))

# Create a model using the nn.Sequential API
model = nn.Sequential(
    nn.Linear(4, 4),
    nn.Linear(4, 1)
)
output = model(features)
print(output)

In [ ]:
# Set the model to evaluation mode
model.eval()
validation_loss = 0.0

with torch.no_grad():
  
    for data in validationloader:
    
        outputs = model(data[0])
        loss = criterion(outputs, data[1])
      
        # Sum the current loss to the validation_loss variable
        validation_loss += loss.item()
        
# Calculate the mean loss value
validation_loss_epoch = validation_loss / len(validationloader)
print(validation_loss_epoch)

# Set the model back to training mode
model.train()

In [ ]:
import torchmetrics

In [ ]:
# Create accuracy metric using torch metrics
metric = torchmetrics.Accuracy(task="multiclass", num_classes=3)
for data in dataloader:
    features, labels = data
    outputs = model(features)
    
    # Calculate accuracy over the batch
    acc = metric(outputs, labels.argmax(dim=-1))
    
# Calculate accuracy over the whole epoch
acc = metric.compute()

# Reset the metric for the next epoch 
metric.reset()
plot_errors(model, dataloader)

In [ ]:
# Using the same model, set the dropout probability to 0.8
model = nn.Sequential(nn.Linear(3072, 16),
                      nn.ReLU(),
                      nn.Dropout(p=0.8))
model(input_tensor)

In [ ]:
values = []
for idx in range(10):
    # Randomly sample a learning rate factor between 2 and 4
    factor = np.random.uniform(2,4)
    lr = 10 ** -factor
    
    # Randomly select a momentum between 0.85 and 0.99
    momentum = np.random.uniform(0.85, 0.99)
    
    values.append((lr, momentum))